name: Build-Test

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**/README.md"

env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Init submodules
        run: |
          git config --global url."https://".insteadOf git://
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          include-prerelease: false

      - name: Restore
        run: dotnet restore ClassicUO.sln

      - name: Build
        run: dotnet build ClassicUO.sln -c Release --no-restore

      - name: Test
        run: dotnet test ClassicUO.sln -c Release --no-build --verbosity normal
        continue-on-error: true
